function values = getExportValues(patient, study, series, file, sequenceNumber)
% values = getExportValues(patient, study, series, file, sequenceNumber)
% uses the patient, study, series, and file to determine what to print in
% each cell for a row for the csv export
% required by GIANT

pixelArea = file.getPixelArea();
[csas, ~] = file.pixelCounts.getStats(pixelArea);

values = struct(...
    'patientId', patient.patientId,...
    'patientSex', file.dicomInfo.PatientSex,...
    'patientDob', '',...
    'sequenceNumber', sequenceNumber,...
    'studyDate', file.date.stringForCsv(),...
    'modality', file.dicomInfo.Modality,...
    'studyName', study.name,...
    'seriesName', series.name,...
    'fileName', file.name,...
    'leftFatCsa', csas.left.high,...
    'leftMuscleCsa', csas.left.mid,...
    'leftLowCsa', csas.left.low,...
    'rightFatCsa', csas.right.high,...
    'rightMuscleCsa', csas.right.mid,...
    'rightLowCsa', csas.right.low);

end
