function values = getExportValues(patient, study, series, file, sequenceNumber)
% values = getExportValues(patient, study, series, file, sequenceNumber)
% uses the patient, study, series, and file to determine what to print in
% each cell for a row for the csv export
% required by GIANT

[csas, ~] = file.getStats();

values = struct(...
    'patientId', patient.patientId,...
    'patientSex', file.dicomInfo.PatientSex,...
    'patientDob', '',...
    'sequenceNumber', sequenceNumber,...
    'studyDate', file.date.stringForCsv(),...
    'modality', file.dicomInfo.Modality,...
    'studyName', study.name,...
    'seriesName', series.name,...
    'fileName', file.name,...
    'leftCsa', csas.left.all,...
    'leftFatCsa', csas.left.fat,...
    'leftMuscleCsa', csas.left.muscle,...
    'rightCsa', csas.right.all,...
    'rightFatCsa', csas.right.fat,...
    'rightMuscleCsa', csas.right.muscle);

end
